### ISSUE TITLE
Duplicate in a folder

### ISSUE THREAD

**Issue by baalan92** [limkokhole/find_similar_image#1]
How can I find the duplicate images in a folder which contains multiple duplicates images?

**Comment by limkokhole** [comment]
This is the basic command:

`python3 similar_img.py foo.png -d folder_path -md 1 -p 100`

More option please check `python3 similar_img.py --help`

Note that I only test it in Linux, neither Windows nor Mac tested.

**Comment by baalan92** [comment]
@limkokhole , Thank you. I used this `python3 similar_img.py test_17.JPEG -d /home/user/images -md 1 -p 100` command on ubuntu 18.04 server with python `Python 3.6.8`. ut I got this on terminal `No such image file exists. Abort.`

**Comment by limkokhole** [comment]
Please ensure the test_17.JPEG image file exist in current path (since you didn't specific full path) and you have the permission to open the image. Or you can add `print(traceback.format_exc())` on above of that error (line 426th at this moment) in the python script to get more info.

**Comment by limkokhole** [comment]
No update from OP for few months.
