### ISSUE TITLE
Note that `future` package is required

### ISSUE THREAD

**Issue by rootwork** [limkokhole/find_similar_image#3]
When I tried running the script I got:

`ModuleNotFoundError: No module named 'past'`

`past` is part of [`future`](https://python-future.org/quickstart.html). I'd recommend adding a note to install it (`pip install future`) as a first step.

Thanks for the script!

**Comment by rootwork** [comment]
Looks like `opencv-python` and `scipy` were also both required.

**Comment by limkokhole** [comment]
Thanks for the report. 

commit 6075ad857ddf63b0f1804114aac43bccddc7b7c6

**Comment by mrjittuu** [comment]
how to install future

**Comment by limkokhole** [comment]
> how to install future

`python3 -m pip install -r requirements.txt`
